name: Package and release development builds

on:
  push:
    tags:
      - 'v*.*-*'
      - 'v*.*.*-*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          ref: development

      - name: Package and release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g 1.13.5 -w 0

      - name: Package and release for Retail
        uses: BigWigsMods/packager@master
        with:
          args: -w wowi-id 0
